apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-servers
nameSuffix: -daan
labels:
  - pairs:
      app.kubernetes.io/instance: daan
    includeSelectors: true
resources:
  - ../../base
patches:
  - path: patch.yaml
  - target:
      kind: IngressRouteUDP
      name: bedrock
    patch: |-
      - op: replace
        path: /spec/entryPoints/0
        value: mc-daan
      - op: replace
        path: /spec/routes/0/services/0/name
        value: bedrock-daan
