apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock
spec:
  template:
    spec:
      containers:
        - name: bedrock
          env:
            - name: SERVER_NAME
              value: PLASKUTJE
            - name: LEVEL_NAME
              value: anuskontklepje
            - name: GAMEMODE
              value: creative
            - name: DIFFICULTY
              value: peaceful
            - name: ALLOW_CHEATS
              value: "true"
            - name: MAX_PLAYERS
              value: "10"
            - name: ONLINE_MODE
              value: "true"
            - name: ALLOW_LIST_USERS
              value: DecidingTiara99:2535442332074978,Gjdeb:2533274863407504,PancakeNL8261:2533274926013414
            - name: DEFAULT_PLAYER_PERMISSION_LEVEL
              value: operator
            - name: LEVEL_TYPE
              value: FLAT
            - name: VIEW_DISTANCE
              value: "96"
