apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bedrock-data
  labels:
    app.kubernetes.io/name: bedrock
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
